services:
  - type: web
    name: cultural-projects
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: APP_NAME
        value: CulturalSystem
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:ضع_مفتاح_التطبيق_هنا
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://cultural-projects.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-little-bird-za81fm0r-pooler.c-2.eu-west-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_0UkFT9VJpCfY
      - key: DB_SSLMODE
        value: require
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        value: ff3503844e7122e0bc9822a4f7655809
      - key: AWS_SECRET_ACCESS_KEY
        value: 197d4f680bacfe8437f9c93581943d4e54810b169cb4c9cd8bd1d9eda4d044be
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: cultural-public
      - key: AWS_ENDPOINT
        value: https://hmevzsgznrfafovymwef.storage.supabase.co/storage/v1/s3
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: true